name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ashrash290/toggleanything:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    env:
      LOG_PREFIX: 'Toggle-anything:'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Removing previous running containers 
        run: docker ps -a | grep -v CONTAINER | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
        
      - name: Removing previous images 
        run: docker image ls -q | xargs -I {} docker image rm -f {}
        
      - name: Pull image
        run: docker pull ashrash290/toggleanything:latest

      - name: Deploy image
        run: docker run -p 3000:3000 -e LOG_PREFIX='${{ env.LOG_PREFIX }}'  -d ashrash290/toggleanything:latest
